server:
  port: 8001


# eureka 配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://jorian:123456@localhost:8761/eureka
logging:
  level:
    root: INFO

spring:
  application:
    name: j-cloud-consumer
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment: #配置rabbimq连接环境
            spring:
              rabbitmq:
                host: localhost
                username: guest
                password: guest
                virtual-host: /
      bindings:
        output:
          destination: Subscribe  #exchange名称，交换模式默认是topic
          content-type: application/json
        input:
          destination: Publisher
          content-type: application/json
  redis:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        min-idle: 0
        max-idle: 8
        database: 8
    host: localhost
    port: 6379
    timeout: 10000
