server:
  port: 8801

spring:
  application:
    name: j-cloud-rabbit-service
#    cloud:
#      stream:
#        binders:
#          rabbit1:
#            type: rabbit
#            environment:
#              spring:
#                rabbitmq:
#                  addresses: localhost
#                  port: 5672
#                  username: admin
#                  password: admin
##                  virtual-host: /unicode-pay
#        bindings:
#          testOutPut:
#            destination: testRabbit
#            content-type: application/json
#            default-binder: rabbit1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
#  instance:
#    lease-renewal-interval-in-seconds: 2 # 设置心跳的间隔时间，默认30
#    lease-expiration-duration-in-seconds: 5 # 超过5秒间隔，默认90
#    instance-id: send-8801.com # 主机名
#    prefer-ip-address: true # 显示ip

